max_jobeet:
    resource: "@MaxJobeetBundle/Controller/"
    type:     annotation
    prefix:   /

max_jobeet2:
    resource: "@MaxJobeetBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin    