security:
    providers:
        # in_memory:
        #     memory:
        #         users:
        #             admin: { password: 123, roles: [ 'ROLE_ADMIN' ] }
        main:
           entity: { class: Max\JobeetBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            anonymous: ~
            form_login: 
              login_path: /login
              check_path: /login_check
            logout:
                path:   /logout
                target: /

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Max\JobeetBundle\Entity\User: sha512